# ST-788: REQ-005 - Dockerfile for SafeTrekr Marketing Site
#
# Multi-stage build for Next.js standalone output.
# Target: < 200MB final image on node:22-alpine.
#
# Build:  docker build -t safetrekr-marketing .
# Run:    docker run -p 3000:3000 safetrekr-marketing

# ---------------------------------------------------------------------------
# Stage 1: Install production + dev dependencies (needed for build)
# ---------------------------------------------------------------------------
FROM node:22-alpine AS deps

# libc6-compat is required for native modules (sharp, etc.) on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy dependency manifests first for layer caching
COPY package.json package-lock.json ./

RUN npm ci

# ---------------------------------------------------------------------------
# Stage 2: Build the Next.js application
# ---------------------------------------------------------------------------
FROM node:22-alpine AS builder

WORKDIR /app

# Bring in the full node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files needed for the build
COPY . .

# Disable Next.js anonymous telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ---------------------------------------------------------------------------
# Stage 3: Production runner -- minimal image, non-root user
# ---------------------------------------------------------------------------
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user and group for running the application
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets (if they exist). The standalone output does not include
# the public/ folder or the static build artifacts, so we bring them in
# explicitly. The mkdir ensures the COPY never fails if public/ is absent.
RUN mkdir -p /app/public
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Copy the standalone server and its bundled node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy the static assets generated by the build
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Run as non-root
USER nextjs

CMD ["node", "server.js"]
